import { MemberProfile, Venue } from "./types";

export const members: MemberProfile[] = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    role: "Founder & CEO, Meridian Labs",
    avatarInitials: "SC",
    isAuroraMember: true,
    preferences: {
      dietary: ["pescatarian", "no shellfish"],
      cuisineAffinities: ["Japanese", "French", "Mediterranean"],
      cuisineAversions: ["Steakhouse", "BBQ"],
      ambiancePreference: "intimate",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["SoHo", "West Village"],
      neighborhoodAvoidances: ["Times Square", "Midtown East"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 19:00-23:00"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "low",
        sleepScore: 85,
        recoveryScore: 88,
      },
    },
  },
  {
    id: "marcus-rivera",
    name: "Marcus Rivera",
    role: "Managing Partner, Theorem Capital",
    avatarInitials: "MR",
    isAuroraMember: true,
    preferences: {
      dietary: [],
      cuisineAffinities: ["Steakhouse", "Italian", "American"],
      cuisineAversions: ["Vegan", "Raw"],
      ambiancePreference: "lively",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["Tribeca", "FiDi"],
      neighborhoodAvoidances: ["Upper East Side"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 20:00-23:00"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "moderate",
        sleepScore: 72,
        recoveryScore: 65,
      },
    },
  },
  {
    id: "anika-patel",
    name: "Anika Patel",
    role: "Co-Founder, Vantage AI",
    avatarInitials: "AP",
    isAuroraMember: true,
    preferences: {
      dietary: ["vegan", "gluten-free"],
      cuisineAffinities: ["Plant-forward", "Mediterranean", "Japanese"],
      cuisineAversions: ["Steakhouse", "French (traditional)"],
      ambiancePreference: "private-dining",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["West Village", "Greenwich Village"],
      neighborhoodAvoidances: ["FiDi", "Midtown"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 18:30-22:30"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "low",
        sleepScore: 90,
        recoveryScore: 91,
      },
    },
  },
  {
    id: "james-whitfield",
    name: "James Whitfield",
    role: "CFO, Theorem Capital",
    avatarInitials: "JW",
    isAuroraMember: false,
    preferences: {
      dietary: ["no pork"],
      cuisineAffinities: [],
      cuisineAversions: [],
      ambiancePreference: "quiet",
      priceFloor: "$$$",
      neighborhoodPreferences: [],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 18:00-23:30"],
        blocked: [],
      },
    },
  },
];

export const venues: Venue[] = [
  {
    id: "venue-1",
    name: "Nami Nori",
    cuisine: "Japanese",
    neighborhood: "West Village",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: false,
    capacity: 8,
    dietaryAccommodations: [
      "pescatarian",
      "vegan",
      "gluten-free",
      "no shellfish options",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Priority seating, complimentary sake flight, dedicated omakase counter",
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:00"],
  },
  {
    id: "venue-2",
    name: "Via Carota",
    cuisine: "Italian",
    neighborhood: "West Village",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: false,
    capacity: 6,
    dietaryAccommodations: [
      "pescatarian",
      "vegan options",
      "gluten-free options",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 20:00", "2026-04-11 20:30"],
  },
  {
    id: "venue-3",
    name: "Shukette",
    cuisine: "Mediterranean",
    neighborhood: "SoHo",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: true,
    capacity: 10,
    dietaryAccommodations: [
      "pescatarian",
      "vegan",
      "gluten-free",
      "no shellfish",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Private dining room, custom tasting menu, sommelier pairing",
    availableSlots: ["2026-04-11 19:00", "2026-04-11 20:00"],
  },
  {
    id: "venue-4",
    name: "Le Coucou",
    cuisine: "French",
    neighborhood: "SoHo",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: true,
    capacity: 12,
    dietaryAccommodations: [
      "pescatarian",
      "limited vegan",
      "gluten-free adaptable",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:30"],
  },
  {
    id: "venue-5",
    name: "Cote",
    cuisine: "Korean Steakhouse",
    neighborhood: "Flatiron",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: true,
    capacity: 8,
    dietaryAccommodations: [
      "limited pescatarian",
      "no vegan options",
      "gluten-free",
      "no pork options",
    ],
    auroraEdge: true,
    auroraPerks: "Butcher's Feast upgrade, priority reservation, wine credit",
    availableSlots: ["2026-04-11 20:00", "2026-04-11 21:00"],
  },
  {
    id: "venue-6",
    name: "Avant Garden",
    cuisine: "Plant-forward",
    neighborhood: "East Village",
    priceRange: "$$$",
    ambiance: "intimate",
    privateRoom: false,
    capacity: 6,
    dietaryAccommodations: [
      "vegan",
      "gluten-free",
      "no shellfish",
      "no pork",
      "pescatarian",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:00", "2026-04-11 20:30"],
  },
  {
    id: "venue-7",
    name: "Atomix",
    cuisine: "Korean Tasting",
    neighborhood: "Midtown East",
    priceRange: "$$$$",
    ambiance: "private-dining",
    privateRoom: true,
    capacity: 8,
    dietaryAccommodations: [
      "pescatarian adaptable",
      "limited vegan",
      "no shellfish with notice",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Extended tasting menu, chef's table experience, sake pairing included",
    availableSlots: ["2026-04-11 19:00"],
  },
  {
    id: "venue-8",
    name: "abcV",
    subtitle: "by Jean-Georges Vongerichten",
    cuisine: "Vegetable-forward",
    neighborhood: "Flatiron",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: true,
    capacity: 10,
    dietaryAccommodations: [
      "vegan",
      "gluten-free",
      "pescatarian",
      "no shellfish",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:00"],
  },
];

export const defaultEventDetails = {
  type: "dinner" as const,
  location: "New York City",
  date: "2026-04-11",
  timeWindow: "19:00 - 23:00",
  groupSize: 4,
  vibe: "Celebratory dinner for a Series B close",
};

// ── Travel scenario ──

export const travelMembers: MemberProfile[] = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    role: "Founder & CEO, Meridian Labs",
    avatarInitials: "SC",
    isAuroraMember: true,
    preferences: {
      dietary: ["pescatarian"],
      cuisineAffinities: ["Japanese", "Mediterranean"],
      cuisineAversions: [],
      ambiancePreference: "boutique",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["Beachfront", "Clifftop"],
      neighborhoodAvoidances: ["Party district"],
      accessibility: [],
      schedule: {
        available: ["2026-05-15 to 2026-05-19"],
        blocked: ["2026-05-20"],
      },
      healthSignals: {
        stressLevel: "high",
        sleepScore: 68,
        recoveryScore: 62,
      },
    },
  },
  {
    id: "marcus-rivera",
    name: "Marcus Rivera",
    role: "Managing Partner, Theorem Capital",
    avatarInitials: "MR",
    isAuroraMember: true,
    preferences: {
      dietary: [],
      cuisineAffinities: ["Steakhouse", "Italian"],
      cuisineAversions: [],
      ambiancePreference: "resort",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["Golf course", "Marina"],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-05-16 to 2026-05-19"],
        blocked: ["2026-05-15"],
      },
      healthSignals: {
        stressLevel: "moderate",
        sleepScore: 72,
        recoveryScore: 65,
      },
    },
  },
  {
    id: "elena-chen",
    name: "Elena Chen",
    role: "Sarah's partner",
    avatarInitials: "EC",
    isAuroraMember: false,
    preferences: {
      dietary: ["vegetarian"],
      cuisineAffinities: [],
      cuisineAversions: [],
      ambiancePreference: "spa-focused",
      priceFloor: "$$$",
      neighborhoodPreferences: [],
      neighborhoodAvoidances: [],
      accessibility: ["ground-floor", "wheelchair-accessible"],
      schedule: {
        available: ["2026-05-15 to 2026-05-19"],
        blocked: [],
      },
    },
  },
  {
    id: "james-whitfield",
    name: "James Whitfield",
    role: "CFO, Theorem Capital",
    avatarInitials: "JW",
    isAuroraMember: false,
    preferences: {
      dietary: ["no pork"],
      cuisineAffinities: [],
      cuisineAversions: [],
      ambiancePreference: "quiet",
      priceFloor: "$$$",
      neighborhoodPreferences: [],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-05-15 to 2026-05-20"],
        blocked: [],
      },
    },
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    role: "General Counsel, Meridian Labs",
    avatarInitials: "PS",
    isAuroraMember: true,
    preferences: {
      dietary: ["vegetarian", "no dairy"],
      cuisineAffinities: ["Indian", "Mediterranean", "Japanese"],
      cuisineAversions: [],
      ambiancePreference: "boutique",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["Beachfront"],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-05-15 to 2026-05-19"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "moderate",
        sleepScore: 78,
        recoveryScore: 70,
      },
    },
  },
  {
    id: "david-kim",
    name: "David Kim",
    role: "Head of Product, Meridian Labs",
    avatarInitials: "DK",
    isAuroraMember: false,
    preferences: {
      dietary: [],
      cuisineAffinities: ["Korean", "Japanese"],
      cuisineAversions: [],
      ambiancePreference: "resort",
      priceFloor: "$$$",
      neighborhoodPreferences: [],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-05-16 to 2026-05-19"],
        blocked: ["2026-05-15"],
      },
    },
  },
];

export const lodgings: Venue[] = [
  {
    id: "lodge-1",
    name: "Amanyara",
    subtitle: "Turks & Caicos",
    cuisine: "Luxury Resort",
    neighborhood: "Northwest Point",
    priceRange: "$$$$",
    ambiance: "boutique",
    privateRoom: true,
    capacity: 8,
    venueType: "lodging",
    nightlyRate: "$3,200/night",
    roomTypes: ["Ocean Pavilion", "Beach Villa", "Pool Villa"],
    features: ["Private beach", "Spa", "Snorkeling reef", "Chef's table dining"],
    dietaryAccommodations: ["All dietary needs", "Private chef available", "Vegetarian menu", "Pescatarian"],
    auroraEdge: true,
    auroraPerks: "Complimentary spa credits, private boat charter, airport transfer via helicopter",
    availableSlots: ["2026-05-15 to 2026-05-19"],
  },
  {
    id: "lodge-2",
    name: "COMO Parrot Cay",
    subtitle: "Turks & Caicos",
    cuisine: "Wellness Resort",
    neighborhood: "Private Island",
    priceRange: "$$$$",
    ambiance: "spa-focused",
    privateRoom: true,
    capacity: 6,
    venueType: "lodging",
    nightlyRate: "$2,800/night",
    roomTypes: ["Beach House", "Two-Bedroom Beach House", "Garden Villa"],
    features: ["Holistic spa", "Yoga pavilion", "Private island", "Farm-to-table dining"],
    dietaryAccommodations: ["Wellness cuisine", "Vegetarian", "Vegan", "Gluten-free", "No pork"],
    auroraEdge: false,
    availableSlots: ["2026-05-15 to 2026-05-19"],
  },
  {
    id: "lodge-3",
    name: "Grace Bay Club",
    subtitle: "Turks & Caicos",
    cuisine: "Beachfront Resort",
    neighborhood: "Grace Bay",
    priceRange: "$$$$",
    ambiance: "resort",
    privateRoom: true,
    capacity: 10,
    venueType: "lodging",
    nightlyRate: "$1,900/night",
    roomTypes: ["Estate Suite", "Penthouse", "Two-Bedroom Suite"],
    features: ["Grace Bay Beach", "Golf nearby", "Kids club", "Multiple restaurants"],
    dietaryAccommodations: ["All dietary needs", "Multiple restaurants on-site", "No pork options"],
    auroraEdge: true,
    auroraPerks: "Suite upgrade, priority dining reservations, private cabana",
    availableSlots: ["2026-05-15 to 2026-05-20"],
  },
  {
    id: "lodge-4",
    name: "The Shore Club",
    subtitle: "Turks & Caicos",
    cuisine: "Modern Resort",
    neighborhood: "Long Bay",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: true,
    capacity: 8,
    venueType: "lodging",
    nightlyRate: "$2,400/night",
    roomTypes: ["Ocean Front Suite", "Penthouse", "Garden Suite"],
    features: ["Rooftop pool", "Nightlife", "Surfing", "Nobu restaurant"],
    dietaryAccommodations: ["Japanese cuisine", "Pescatarian", "Vegetarian options", "No pork"],
    auroraEdge: false,
    availableSlots: ["2026-05-16 to 2026-05-20"],
  },
  {
    id: "lodge-5",
    name: "Wymara Resort",
    subtitle: "Turks & Caicos",
    cuisine: "Boutique Resort",
    neighborhood: "Grace Bay",
    priceRange: "$$$",
    ambiance: "boutique",
    privateRoom: true,
    capacity: 6,
    venueType: "lodging",
    nightlyRate: "$950/night",
    roomTypes: ["Ocean View Suite", "Deluxe Room", "One-Bedroom Suite"],
    features: ["Infinity pool", "Beach access", "Spa", "Intimate scale"],
    dietaryAccommodations: ["Vegetarian", "Pescatarian", "Gluten-free"],
    auroraEdge: false,
    availableSlots: ["2026-05-15 to 2026-05-19"],
  },
];

export const travelEventDetails = {
  type: "travel" as const,
  location: "Turks & Caicos",
  date: "2026-05-15",
  timeWindow: "May 15-19 (4 nights)",
  groupSize: 6,
  vibe: "Post-fundraise reset — decompression trip for the founding team and partners",
};

// ── Flight coordination data ──

import { FlightInfo, DisruptionScenario } from "./types";

export const travelFlights: FlightInfo[] = [
  {
    participantId: "sarah-chen",
    participantName: "Sarah Chen",
    departureAirport: "TEB",
    departureCity: "Teterboro, NJ",
    flightType: "private",
    departureTime: "2026-05-15T08:00",
    arrivalTime: "2026-05-15T12:30",
    arrivalAirport: "PLS",
    transferGroup: 1,
    status: "confirmed",
  },
  {
    participantId: "elena-chen",
    participantName: "Elena Chen",
    departureAirport: "TEB",
    departureCity: "Teterboro, NJ",
    flightType: "private",
    departureTime: "2026-05-15T08:00",
    arrivalTime: "2026-05-15T12:30",
    arrivalAirport: "PLS",
    transferGroup: 1,
    status: "confirmed",
  },
  {
    participantId: "priya-sharma",
    participantName: "Priya Sharma",
    departureAirport: "JFK",
    departureCity: "New York, NY",
    flightType: "commercial",
    flightNumber: "AA 1847",
    departureTime: "2026-05-15T06:15",
    arrivalTime: "2026-05-15T11:45",
    arrivalAirport: "PLS",
    transferGroup: 1,
    status: "confirmed",
  },
  {
    participantId: "marcus-rivera",
    participantName: "Marcus Rivera",
    departureAirport: "JFK",
    departureCity: "New York, NY",
    flightType: "commercial",
    flightNumber: "DL 983",
    departureTime: "2026-05-16T07:00",
    arrivalTime: "2026-05-16T12:15",
    arrivalAirport: "PLS",
    transferGroup: 2,
    status: "confirmed",
  },
  {
    participantId: "james-whitfield",
    participantName: "James Whitfield",
    departureAirport: "JFK",
    departureCity: "New York, NY",
    flightType: "commercial",
    flightNumber: "DL 983",
    departureTime: "2026-05-16T07:00",
    arrivalTime: "2026-05-16T12:15",
    arrivalAirport: "PLS",
    transferGroup: 2,
    status: "confirmed",
  },
  {
    participantId: "david-kim",
    participantName: "David Kim",
    departureAirport: "LAX",
    departureCity: "Los Angeles, CA",
    flightType: "commercial",
    flightNumber: "UA 2241",
    departureTime: "2026-05-16T05:30",
    arrivalTime: "2026-05-16T15:45",
    arrivalAirport: "PLS",
    transferGroup: 3,
    status: "confirmed",
  },
];

export const disruptionScenario: DisruptionScenario = {
  triggerId: "weather-delay-jfk",
  triggerLabel: "JFK Weather Hold — DL 983 delayed 3 hours",
  affectedParticipants: ["marcus-rivera", "james-whitfield"],
  originalArrival: "2026-05-16T12:15",
  newArrival: "2026-05-16T15:15",
  delayMinutes: 180,
  cause: "Severe thunderstorm warning — FAA ground stop at JFK, expected to lift by 10:00 ET",
  cascadingImpacts: [
    { text: "Marcus & James miss the 12:30 PM group lunch at Grace Bay Club", severity: "red" },
    { text: "Transfer Group 2 needs rescheduling from 12:45 PM to ~15:45 PM", severity: "amber" },
    { text: "David (LAX, arriving 15:45) and delayed JFK pair now arrive within 30 min — can share transfer", severity: "green" },
    { text: "Sunset sailing excursion at 16:00 — 2 of 6 participants absent", severity: "amber" },
    { text: "Room keys for Marcus and James — request early digital check-in", severity: "blue" },
  ],
  resolutionOptions: [
    {
      id: "option-a",
      title: "Merge Transfer Groups",
      description: "Combine delayed JFK pair (Marcus & James, ~15:15) with LAX arrival (David, 15:45). Single resort shuttle at 16:00. Cancel original 12:45 transfer.",
      confidence: 92,
      tradeoff: "David waits ~15 min at airport. Group saves $180 on separate transfer.",
    },
    {
      id: "option-b",
      title: "Rebook Sailing to Day 2",
      description: "Move sunset sailing from May 16 at 16:00 to May 17 at 16:00. Full group participation. Backfill May 16 afternoon with spa for the 3 already on-island.",
      confidence: 87,
      tradeoff: "Day 2 schedule gets tighter. Sarah's beach time moves to morning.",
    },
    {
      id: "option-c",
      title: "Split Day Itinerary",
      description: "Keep sailing at 16:00 for the 4 on-island. Marcus and James get a private welcome dinner instead of group sailing.",
      confidence: 74,
      tradeoff: "Group split on first shared activity. Marcus may feel excluded from bonding moment.",
    },
  ],
  strategistBriefing:
    "DISRUPTION: DL 983 (JFK→PLS) delayed 3h due to FAA ground stop. Affects Marcus Rivera and James Whitfield — new arrival ~15:15. RECOMMENDED: Option A (merge transfers) + Option B (rebook sailing to Day 2). Elena's wheelchair-accessible transfer is unaffected (arrived Day 1 via private from TEB). Sarah's Oura data shows elevated stress — avoid adding schedule pressure on her first full day. Budget impact: -$180 transfer savings. ACTION NEEDED: Confirm sailing rebooking with operator, arrange merged 16:00 airport transfer, send push notification to Marcus and James with updated ETA.",
};
