import { MemberProfile, Venue } from "./types";

export const members: MemberProfile[] = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    role: "Founder & CEO, Meridian Labs",
    avatarInitials: "SC",
    isAuroraMember: true,
    preferences: {
      dietary: ["pescatarian", "no shellfish"],
      cuisineAffinities: ["Japanese", "French", "Mediterranean"],
      cuisineAversions: ["Steakhouse", "BBQ"],
      ambiancePreference: "intimate",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["SoHo", "West Village"],
      neighborhoodAvoidances: ["Times Square", "Midtown East"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 19:00-23:00"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "low",
        sleepScore: 85,
        recoveryScore: 88,
      },
    },
  },
  {
    id: "marcus-rivera",
    name: "Marcus Rivera",
    role: "Managing Partner, Theorem Capital",
    avatarInitials: "MR",
    isAuroraMember: true,
    preferences: {
      dietary: [],
      cuisineAffinities: ["Steakhouse", "Italian", "American"],
      cuisineAversions: ["Vegan", "Raw"],
      ambiancePreference: "lively",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["Tribeca", "FiDi"],
      neighborhoodAvoidances: ["Upper East Side"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 20:00-23:00"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "moderate",
        sleepScore: 72,
        recoveryScore: 65,
      },
    },
  },
  {
    id: "anika-patel",
    name: "Anika Patel",
    role: "Co-Founder, Vantage AI",
    avatarInitials: "AP",
    isAuroraMember: true,
    preferences: {
      dietary: ["vegan", "gluten-free"],
      cuisineAffinities: ["Plant-forward", "Mediterranean", "Japanese"],
      cuisineAversions: ["Steakhouse", "French (traditional)"],
      ambiancePreference: "private-dining",
      priceFloor: "$$$$",
      neighborhoodPreferences: ["West Village", "Greenwich Village"],
      neighborhoodAvoidances: ["FiDi", "Midtown"],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 18:30-22:30"],
        blocked: [],
      },
      healthSignals: {
        stressLevel: "low",
        sleepScore: 90,
        recoveryScore: 91,
      },
    },
  },
  {
    id: "james-whitfield",
    name: "James Whitfield",
    role: "CFO, Theorem Capital",
    avatarInitials: "JW",
    isAuroraMember: false,
    preferences: {
      dietary: ["no pork"],
      cuisineAffinities: [],
      cuisineAversions: [],
      ambiancePreference: "quiet",
      priceFloor: "$$$",
      neighborhoodPreferences: [],
      neighborhoodAvoidances: [],
      accessibility: [],
      schedule: {
        available: ["2026-04-11 18:00-23:30"],
        blocked: [],
      },
    },
  },
];

export const venues: Venue[] = [
  {
    id: "venue-1",
    name: "Nami Nori",
    cuisine: "Japanese",
    neighborhood: "West Village",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: false,
    capacity: 8,
    dietaryAccommodations: [
      "pescatarian",
      "vegan",
      "gluten-free",
      "no shellfish options",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Priority seating, complimentary sake flight, dedicated omakase counter",
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:00"],
  },
  {
    id: "venue-2",
    name: "Via Carota",
    cuisine: "Italian",
    neighborhood: "West Village",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: false,
    capacity: 6,
    dietaryAccommodations: [
      "pescatarian",
      "vegan options",
      "gluten-free options",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 20:00", "2026-04-11 20:30"],
  },
  {
    id: "venue-3",
    name: "Shukette",
    cuisine: "Mediterranean",
    neighborhood: "SoHo",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: true,
    capacity: 10,
    dietaryAccommodations: [
      "pescatarian",
      "vegan",
      "gluten-free",
      "no shellfish",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Private dining room, custom tasting menu, sommelier pairing",
    availableSlots: ["2026-04-11 19:00", "2026-04-11 20:00"],
  },
  {
    id: "venue-4",
    name: "Le Coucou",
    cuisine: "French",
    neighborhood: "SoHo",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: true,
    capacity: 12,
    dietaryAccommodations: [
      "pescatarian",
      "limited vegan",
      "gluten-free adaptable",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:30"],
  },
  {
    id: "venue-5",
    name: "Cote",
    cuisine: "Korean Steakhouse",
    neighborhood: "Flatiron",
    priceRange: "$$$$",
    ambiance: "lively",
    privateRoom: true,
    capacity: 8,
    dietaryAccommodations: [
      "limited pescatarian",
      "no vegan options",
      "gluten-free",
      "no pork options",
    ],
    auroraEdge: true,
    auroraPerks: "Butcher's Feast upgrade, priority reservation, wine credit",
    availableSlots: ["2026-04-11 20:00", "2026-04-11 21:00"],
  },
  {
    id: "venue-6",
    name: "Avant Garden",
    cuisine: "Plant-forward",
    neighborhood: "East Village",
    priceRange: "$$$",
    ambiance: "intimate",
    privateRoom: false,
    capacity: 6,
    dietaryAccommodations: [
      "vegan",
      "gluten-free",
      "no shellfish",
      "no pork",
      "pescatarian",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:00", "2026-04-11 20:30"],
  },
  {
    id: "venue-7",
    name: "Atomix",
    cuisine: "Korean Tasting",
    neighborhood: "Midtown East",
    priceRange: "$$$$",
    ambiance: "private-dining",
    privateRoom: true,
    capacity: 8,
    dietaryAccommodations: [
      "pescatarian adaptable",
      "limited vegan",
      "no shellfish with notice",
      "no pork",
    ],
    auroraEdge: true,
    auroraPerks: "Extended tasting menu, chef's table experience, sake pairing included",
    availableSlots: ["2026-04-11 19:00"],
  },
  {
    id: "venue-8",
    name: "abcV",
    subtitle: "by Jean-Georges Vongerichten",
    cuisine: "Vegetable-forward",
    neighborhood: "Flatiron",
    priceRange: "$$$$",
    ambiance: "intimate",
    privateRoom: true,
    capacity: 10,
    dietaryAccommodations: [
      "vegan",
      "gluten-free",
      "pescatarian",
      "no shellfish",
      "no pork",
    ],
    auroraEdge: false,
    availableSlots: ["2026-04-11 19:30", "2026-04-11 20:00"],
  },
];

export const defaultEventDetails = {
  type: "dinner" as const,
  location: "New York City",
  date: "2026-04-11",
  timeWindow: "19:00 - 23:00",
  groupSize: 4,
  vibe: "Celebratory dinner for a Series B close",
};
